---
title: "Project - EDA"
author: "Addison Shay"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load data
library(readr)
online <- read_csv("C:/Users/amsha/OneDrive - Umich/Documents/Winter 2020/STATS 503/Project/online_shoppers_intention.csv")


#factorize categorical
online$Month = factor(online$Month)
online$VisitorType = factor(online$VisitorType)
online$Weekend = factor(online$Weekend)
online$Revenue = factor(online$Revenue)

#split 70-30
#want even amounts of YES/NO for Revenue
revenue_yes = which(online$Revenue == 'TRUE')
revenue_no = which(online$Revenue == 'FALSE')
set.seed(630)

train_id = c(sample(revenue_yes, size = trunc(0.7 * length(revenue_yes))), sample(revenue_no, size = trunc(0.7 * length(revenue_no))))
training = online[train_id, ]
testing = online[-train_id, ]

summary(training)


#Meeting Notes - 03/20/20
#standardize - quantile normalize. 
#scott - EDA
#addison - trees/random forest & feature importance
#victor - other classification

#classification errors





#Check side-by-side boxplots for numerical variables
library(ggplot2)
library(dplyr)
library(tidyr)
num_var = c("Administrative", "Administrative_Duration", "Informational", "Informational_Duration", "ProductRelated", "ProductRelated_Duration", "BounceRates", "ExitRates", "PageValues", "SpecialDay", "OperatingSystems", "Browser", "Region", "TrafficType")
train.explore = training[, c(num_var, "Revenue")]

train.explore.1 = gather(train.explore, key = "Variable", value = "Value", -c("Revenue"))
ggplot(train.explore.1) + geom_boxplot(aes(x = Revenue, y = Value)) + facet_wrap(.~Variable, scales = "free_y") + theme_minimal()

#Meeting Notes - 03/20/20
#standardize - quantile normalize. 
#scott - EDA
#addison - trees/random forest & feature importance
#victor - other classification

#classification errors

```

